### ISSUE TITLE
rndc-confgen

### ISSUE THREAD

**Issue by pasan1986** [lizj3624/bind-9.10.3-P4#1]
hi,

Im trying to install Bindbind-9.10.1-P2, and when i try to run command "rndc-confgen -b 512", i receive error as "bash: rndc-confgen: command not found"
so i tried to install command but it says "no package available"
Please help me to fix this issue.

Thanks.

**Comment by lizj3624** [comment]
May be rndc-confgen installation path not set env variable "PATH"
1、echo $PATH
2、find / -name rndc-configen，find rndc-configen installation path
3、vim ~/.bash_profile，add "export PATH= 'rndc-configen installation path':$PATH "
4、source ~/.bash_profile
5、try again "rndc-confgen -b 512"
